services:
  db:
    build:
      context: ./db
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file:
      - ./.env 

  kc:
    depends_on:
      - db
    build:
      context: ./kc
    ports:
      - ${KC_HTTP_PORT}:${KC_HTTP_PORT}
      - ${KC_HTTP_MANAGEMENT_PORT}:${KC_HTTP_MANAGEMENT_PORT}
    env_file:
      - ./.env 

  mailhog:
    depends_on:
      - kc
    build:
      context: ./mailhog
    ports:
      - ${MH_UI_BIND_ADDR_PORT}:${MH_UI_BIND_ADDR_PORT}
    env_file:
      - ./.env 

  backend:
    depends_on:
      - kc
    build:
      context: ./backend
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - ./.env 

  frontend:
    depends_on:
      - kc
      - backend
    build:
      context: ./frontend
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    env_file:
      - ./.env 
    volumes:
      - ./frontend/src:/app/src:rw
